Fix send addresses format
witnet/sheikah pull request #1440
Opened 2020-10-04 20:43 UTC by gabaldon

2020-10-04 20:43 UTC, clbartoli commented on src/store/wallet.js
> +      console.log('infoooo', info)
delete

2020-10-05 08:03 UTC, mariocao requested changes

2020-10-05 08:03 UTC, mariocao commented on src/store/wallet.js
> +      console.log(info)
forgot to remote the log?

2020-10-05 08:38 UTC, gabaldon commented
duplicated in #1441

2020-10-05 08:38 UTC, closed without merging