Handle error when trying to send transaction and node is not synced
witnet/sheikah pull request #1479
Opened 2020-10-20 10:12 UTC by gabaldon

close #1469

2020-10-20 15:20 UTC, Tommytrg requested changes
Could you add a test checking the behavior when node is not synced?

2020-10-23 13:56 UTC, clbartoli commented
When the node is not synced, when trying to send the button stays clicked after the Error message

![image](https://user-images.githubusercontent.com/52961116/97012605-4b4b8080-1548-11eb-92a4-8c5450ef5d99.png)

2020-10-26 16:13 UTC, clbartoli approved these changes

2020-10-26 16:14 UTC, Tommytrg approved these changes

2020-10-26 16:16 UTC, merged