Add wallet name feat
witnet/sheikah pull request #1482
Opened 2020-10-22 10:54 UTC by Tommytrg

2020-10-29 15:37 UTC, gabaldon reviewed
You should also add the wallet name to the `walletList` component and to the `NetworkStatus`.

2020-10-29 15:37 UTC, gabaldon commented on src/store/wallet.js
> +        title: context.state.title,
The correct param is 'name' not 'title'.

2020-10-29 15:37 UTC, gabaldon commented on src/components/steps/WalletDescription.vue
> +        this.$store.commit('setWalletDescription', { title: val })
Could you move this to a computed using ...mapState({}) ?

2020-11-05 09:42 UTC, gabaldon requested changes
The wallet name should also appear in the `NetworkStatus` component.

2020-11-10 09:50 UTC, tmpolaczyk commented on src/store/wallet.js
> +        console.log('result:>', request.result)
:)

```suggestion
```

2020-11-10 09:57 UTC, tmpolaczyk commented on tests/unit/src/components/steps/WalletDescription.spec.js
> +    // console.log('AAA', a.props().type)
```suggestion
```

2020-11-10 15:45 UTC, tmpolaczyk commented on src/components/NetworkStatus.vue
> +      console.log('--->', this.unlockedWallet)
```suggestion
```

2020-11-10 17:13 UTC, gabaldon requested changes

2020-11-10 17:13 UTC, gabaldon commented on src/api.js
> +  console.log('response', response)
Please remove console.log

2020-11-10 17:13 UTC, gabaldon commented on src/components/steps/WalletDescription.vue
> +  margin-bottom: 32px;
```suggestion
  margin-bottom: 16px;
```

2020-11-11 08:21 UTC, gabaldon approved these changes

2020-11-11 09:31 UTC, merged