Only close the wallet when Sheikah has run it
witnet/sheikah pull request #1535
Opened 2020-11-20 16:45 UTC by Tommytrg

close #1531

2020-11-23 10:55 UTC, clbartoli submitted a review, later dismissed

2020-11-30 17:22 UTC, gabaldon requested changes

2020-11-30 17:22 UTC, gabaldon commented on src/store/wallet.js
> +      status.defaultWallet = defaultWallet
```suggestion
      status.isDefaultWallet = defaultWallet
```

2020-11-30 17:22 UTC, gabaldon commented on src/background.js
> +      win.webContents.send('running')
Why are you sending this message right above loaded? Doing this you cannot differentiate the two steps.

2020-12-01 10:57 UTC, gabaldon submitted a review, later dismissed

2020-12-01 11:02 UTC, merged