Implement a Dark mode for Sheikah
witnet/sheikah pull request #1595
Opened 2021-01-08 15:10 UTC by gabaldon

This pr implements a component to change the theme to a dark mode. It creates variables related to each theme.
close #1571

2021-01-11 13:03 UTC, aesedepece commented
![image](https://user-images.githubusercontent.com/1316439/104185713-9ec9be00-5415-11eb-98f0-65cf7382592c.png)

Highligh color in select boxes is the same as foreground text color, so it makes the text in the options invisible.

2021-01-11 16:20 UTC, aesedepece commented
![image](https://user-images.githubusercontent.com/1316439/104208791-34267b80-5431-11eb-9bac-f0c27f6130b1.png)

Loading screen is hard to read now.

2021-01-12 09:19 UTC, Tommytrg commented
![image](https://user-images.githubusercontent.com/24905681/104294430-71394f00-54bf-11eb-8ad8-df04d0291af2.png)
Disabled buttons look like enabled ones.

2021-01-12 14:21 UTC, aesedepece approved these changes
All my former comments have been successfully addressed. No further objections from my side.

2021-01-12 17:41 UTC, Tommytrg requested changes
Awesome job, just some considerations:
- Use theme = 'dark' instead of darkTheme = true to be able to add a new theme in the future.
- Make components that handle the theme instead to avoid add unnecessary logic to parent components.
- Avoid make changes that are out of the scope of the PRs to facilitate reviews :cry:

2021-01-12 17:41 UTC, Tommytrg commented on src/components/RadonAggregateTallyScript.vue
> +            v-if="emptyScript && darkMode"
Could you move this to a component?

2021-01-12 17:41 UTC, Tommytrg commented on src/components/RadonAggregateTallyScript.vue
> +            <img v-if="darkMode" src="@/resources/svg/add-operator-dark.svg" />
Could we move this to a component?

2021-01-12 17:41 UTC, Tommytrg commented on src/components/RadonOperator.vue
> +          v-if="darkMode"
Could we move this to a component?

2021-01-12 17:41 UTC, Tommytrg commented on src/components/RadonScript.vue
> +            v-if="emptyScript && darkMode"
Could we move this to a component?

2021-01-12 17:41 UTC, Tommytrg commented on src/components/RadonScript.vue
> +            <img
Could we move this to a component?

2021-01-12 17:41 UTC, Tommytrg commented on src/components/Select.vue
> +                v-if="areOptionsVisible && darkMode"
Could we move this to a component?

2021-01-12 17:41 UTC, Tommytrg commented on src/components/SettingsThemeSwitch.vue
> +      activeTheme: 'Dark',
```suggestion
      themeNames: {
      dark: 'Dark',
      light: 'Light'
      }
```

2021-01-12 17:41 UTC, Tommytrg commented on src/components/SettingsThemeSwitch.vue
> +    :inactive-text="inactiveTheme"
```suggestion
    :active-text="themeNames.dark"
    :inactive-text="themeNames.light"
```

2021-01-12 17:41 UTC, Tommytrg commented on src/components/SettingsThemeSwitch.vue
> +    toggle: {
```suggestion
    activeTheme: {
```

2021-01-12 17:41 UTC, Tommytrg commented on src/components/SettingsThemeSwitch.vue
> +    v-model="toggle"
```suggestion
    v-model="activeTheme"
```

2021-01-12 17:41 UTC, Tommytrg commented on src/store/wallet.js
> +    darkMode: false,
With all the changes you made, we could add easily any theme. To make the most this, I would use a variable called "theme" witch value could be "light" | "dark". With this approach we could update or add a theme easily

2021-01-12 17:41 UTC, Tommytrg commented on src/components/Alert.vue
> -<template>
Spite we need to delete this component, I think it's out the scope of this big PR

2021-01-14 17:53 UTC, Tommytrg approved these changes

2021-01-15 08:58 UTC, merged