Show wallet description
witnet/sheikah pull request #1680
Opened 2021-05-11 08:43 UTC by gabaldon

close #1678

2021-05-13 11:36 UTC, aesedepece requested changes

2021-05-13 11:36 UTC, aesedepece commented on src/store/wallet.js
> +      console.log(state.unlockedWalletDescription)
```suggestion
```

2021-05-13 11:36 UTC, aesedepece commented on src/store/wallet.js
> +        console.log('unlock wallet------>', request.result)
```suggestion
```

2021-05-17 08:08 UTC, clbartoli submitted a review, later dismissed

2021-05-17 08:51 UTC, clbartoli approved these changes

2021-05-17 09:07 UTC, aesedepece approved these changes
Nice!

![image](https://user-images.githubusercontent.com/1316439/118463396-ff3c7500-b6ff-11eb-9f2d-5ce0219708db.png)
![image](https://user-images.githubusercontent.com/1316439/118463299-e764f100-b6ff-11eb-8d0f-732b7066fb53.png)

2021-05-17 09:14 UTC, merged