feat: show expired session info
witnet/sheikah pull request #1682
Opened 2021-05-11 14:22 UTC by gabaldon

This issue is a temporal improvement in the user experience when the session expires. The wallet backend should implement a method for extending the session timeout [#1927](https://github.com/witnet/witnet-rust/issues/1927)

2021-05-11 15:50 UTC, Tommytrg commented on src/components/LogoutModal.vue
> +    :title="this.$t(close_session_info_title)"
```suggestion
    :title="$t(close_session_info_title)"
```

2021-05-11 15:50 UTC, Tommytrg commented on src/components/LogoutModal.vue
> +      <p class="title">{{ this.$t('close_session_info_title') }}</p>
```suggestion
      <p class="title">{{ $t('close_session_info_title') }}</p>
```

2021-05-11 15:51 UTC, Tommytrg commented on src/components/LogoutModal.vue
> +    <el-checkbox v-model="checked">{{ this.$t('not_show_again') }}</el-checkbox>
```suggestion
    <el-checkbox v-model="checked">{{ $t('not_show_again') }}</el-checkbox>
```

2021-05-11 15:51 UTC, Tommytrg commented on src/components/LogoutModal.vue
> +      <el-button type="primary" @click="close">{{ this.$t('ok') }}</el-button>
```suggestion
      <el-button type="primary" @click="close">{{ $t('ok') }}</el-button>
```

2021-05-11 15:53 UTC, Tommytrg commented on src/store/wallet.js
> +      // state.sessionTimeout = setTimeout(() => {
Remove comment

2021-05-11 15:58 UTC, Tommytrg commented on src/api.js
> +
As we are thinking in store more information related to the session expiration I'd rename it with sessionExpirantionPreferences

2021-05-13 11:09 UTC, aesedepece requested changes

2021-05-13 11:11 UTC, aesedepece requested changes

2021-05-13 11:11 UTC, aesedepece commented on src/store/wallet.js
> +      console.log(request)
```suggestion
```

2021-05-13 11:11 UTC, aesedepece commented on src/store/wallet.js
> +        console.log('startSessionTimeout')
```suggestion
```

2021-05-13 11:11 UTC, aesedepece commented on src/store/wallet.js
> +        console.log('error while refreshing session')
```suggestion
        console.error('error while refreshing session', request.result)
```

2021-05-13 13:49 UTC, aesedepece submitted a review, later dismissed

2021-05-17 08:03 UTC, clbartoli approved these changes

2021-05-17 08:11 UTC, merged