feat(ui): select weighted or absolute fee to create VTT
witnet/sheikah pull request #1712
Opened 2021-07-21 10:11 UTC by gabaldon

2021-07-22 11:22 UTC, tmpolaczyk commented on src/store/wallet.js
> +        console.log('result', request.result)
```suggestion
```

2021-07-22 11:22 UTC, tmpolaczyk commented on src/store/wallet.js
> +      console.log('create data request', data)
```suggestion
```

2021-08-09 06:12 UTC, Tommytrg requested changes

2021-08-09 06:12 UTC, Tommytrg commented on src/components/CreateDataRequestForm.vue
> +          })
```suggestion
          this.$emit('create-dr', {
            ...this.form,
            feeType: this.feeType.key,
         })
```

2021-08-09 06:12 UTC, Tommytrg commented on src/components/SendValueTransferForm.vue
> +    // const FEE_TYPE = ['absolute', 'weighted']
```suggestion
```

2021-08-09 06:12 UTC, Tommytrg commented on src/components/SendValueTransferForm.vue
> +      isIndeterminate: true,
What is `isIndeterminate` for?

2021-08-13 11:43 UTC, gabaldon commented
split in #1717 and #1716

2021-08-13 11:43 UTC, closed without merging